# Generated by Django 4.2.28 on 2026-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='gemini_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
